default:
  image: ubuntu:latest

  services:
    - node:18

stages:
  - build
  - test
  - deploy

no_build_yet:
  stage: build
  script:
    - echo SKIP

no_test_yet:
  stage: test
  script:
    - echo SKIP

no_deploy_yet:
  stage: deploy
  script:
    - echo SKIP