default:
  image: node:latest

  services:
    - python:latest

another_default:
  image: docker
  services: 
    - docker:dind
  script:
    - echo "login starts..."
    - echo $CI_REGISTRY_PASSWORD |\
      docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - echo "build image $CI_REGISTRY_IMAGE"
    - docker build -t $CI_REGISTRY_IMAGE .
    - echo "push image"
    - docker push $CI_REGISTRY_IMAGE

stages:
  - build
  - setup_test
  - test
  - deploy

no_build_yet:
  stage: build
  script:
    - echo SKIP

node_version_test:
  stage: setup_test
  script:
    - node -v
  
npm_version_test:
  stage: setup_test
  script:
    - npm -v

python_version_test:
  stage: setup_test
  script:
    - python --version

no_deploy_yet:
  stage: deploy
  script:
    - echo SKIP