stages:
  - build
  - test
  - deploy

image: node:latest

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - apt-get -y update
    - apt-get -y install git
    - apt-get -y install watchman

test:
  stage: test
  script:
    - echo "This job tests node and yarn installation"
    - node --version
    - npm --version
    - yarn --version


deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
    - yarn install
    - npm install --global expo-cli
    - expo --version
    - expo install expo-updates
    - expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
    - expo publish
