default:
  image: node:latest

  services:
    - python:latest

stages:
  - build
  - setup_test
  - test
  - deploy

no_build_yet:
  stage: build
  script:
    - echo SKIP

node_version_test:
  stage: setup_test
  script:
    - node -v
  
npm_version_test:
  stage: setup_test
  script:
    - npm -v

python_version_test:
  stage: setup_test
  script:
    - python --version

no_deploy_yet:
  stage: deploy
  script:
    - echo SKIP