empty-build-job:
  stage: build
  script:
    - echo "This is an empty build job."

empty-test-job1:
  stage: test
  script:
    - echo "This is a empty test job."

empty-test-job2:
  stage: test
  script:
    - echo "This is a empty test job."

deploy-prod:
  stage: deploy
  image: node:latest
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
    - node --version
    - npm --version
    - yarn --version
    - apt-get -y update
    - apt-get -y install git
    - apt-get -y install watchman
    - npm install --global expo-cli
    - expo --version
    - yarn install
    - expo install expo-updates
    - expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
    - expo publish