default:
  image: ubuntu:latest

  services:
    - node:latest

stages:
  - build
  - test
  - deploy

no_build_yet:
  stage: build
  script:
    - echo SKIP

test_if_node_is_present:
  stage: test
  script:
    - echo "before node"
    - node -v
    - echo "after node"

no_deploy_yet:
  stage: deploy
  script:
    - echo SKIP