build-job:
  stage: build
  script:
    - echo "Start Building"
    - npm install --global yarn
    - yarn install
    - echo "Build complete"

test-job1:
  stage: test
  script:
    - echo "This job tests something"

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."