.build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

.test-job1:
  stage: test
  script:
    - echo "This job tests something"

.test-job2:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20

deploy-prod:
  stage: deploy
  image: node:latest
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
    - node --version
    - npm --version
    - apt-get -y update
    - apt-get -y install git
    - apt-get -y install watchman
    - npm install --global expo-cli
    - expo --version
    - expo install expo-updates
    - expo publish